apiVersion: v1
kind: Secret
metadata:
  name: n8n-db-secret
spec:
  type: Opaque
stringData:
  username: n8n
  password: changeme-super-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-encryption
type: Opaque
stringData:
  key: changeme-encryption-key-please-rotate
