apiVersion: v1
kind: Secret
metadata:
  name: n8n-db-storage
type: Opaque
stringData:
  blob-sas: <insert-sas-token>
  container-name: n8n-db
  destination-path: https://storage-account.blob.core.windows.net/n8n-db

---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-db-creds
type: kubernetes.io/basic-auth
stringData:
  username: n8n
  password: changeme-db-password
